from django.contrib import admin
from django.urls import path
from . import views
from . import c
from . import cpp
from . import java
from . import python
from . import html
from . import css

urlpatterns = [
    path('index',views.index,name='home'),
    path('contactus', views.contactus, name='contactus'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('courses', views.courses, name='courses'),
    path('c', views.c, name='c'),
    path('cpp', views.cpp, name='cpp'),
    path('java', views.java, name='java'),
    path('python', views.python, name='python'),
    path('html', views.html, name='html'),
    path('css', views.css, name='css'),
    path('c_introduction',c.introduction,name='c_introduction'),
    path('c_basic_syntax',c.basic_syntax,name='c_basic_syntax'),
    path('c_data_types',c.data_types,name='c_data_types'),
    path('c_operators', c.operators, name='c_operators'),
    path('c_decision_making', c.decision_making, name='c_decision_making'),
    path('c_loops', c.loops, name='c_loops'),
    path('c_function', c.function, name='c_function'),
    path('c_pointer', c.pointer, name='c_pointer'),
    path('c_string', c.pointer, name='c_string'),
    path('c_structure', c.structure, name='c_structure'),
    path('c_file_handling', c.file_handling, name='c_file_handling'),
    path('c_error_handling', c.error_handling, name='c_error_handling'),
    path('c_command_line_argument', c.command_line_argument, name='c_command_line_argument'),
    path('cpp_introduction', cpp.introduction, name='cpp_introduction'),
    path('cpp_basic_syntax', cpp.basic_syntax, name='cpp_basic_syntax'),
    path('cpp_data_types', cpp.data_types, name='cpp_data_types'),
    path('cpp_operators', cpp.operators, name='cpp_operators'),
    path('cpp_decision_making', cpp.decision_making, name='cpp_decision_making'),
    path('cpp_loops', cpp.loops, name='cpp_loops'),
    path('cpp_function', cpp.function, name='cpp_function'),
    path('cpp_array', cpp.array, name='cpp_array'),
    path('cpp_basic_input_output', cpp.basic_input_output, name='cpp_basic_input_output'),
    path('cpp_classes_and_objects', cpp.classes_and_objects, name='cpp_classes_and_objects'),
    path('cpp_inheritance', cpp.inheritance, name='cpp_inheritance'),
    path('cpp_polymorphism', cpp.polymorphism, name='cpp_polymorphism'),
    path('cpp_overloading_and_overriding', cpp.overlaoding_and_overriding, name='cpp_overloading_and_overriding'),
    path('cpp_exception_handling', cpp.exception_handling, name='cpp_exception_handling'),
    path('java_introduction',java.introduction, name='java_introduction'),
    path('java_environment_setup', java.environment_setup, name='java_environment_setup'),
    path('java_basic_syntax', java.basic_syntax, name='java_basic_syntax'),
    path('java_data_types', java.data_types, name='java_data_types'),
    path('java_operators', java.operators, name='java_operators'),
    path('java_decision_making', java.decision_making, name='java_decision_making'),
    path('java_loops', java.loops, name='java_loops'),
    path('java_array', java.array, name='java_array'),
    path('java_string', java.string, name='java_string'),
    path('java_method', java.method, name='java_method'),
    path('java_basic_input_output', java.basic_input_output, name='java_basic_input_output'),
    path('java_file_handling', java.file_handling, name='java_file_handling'),
    path('java_exception_handling', java.exception_handling, name='java_exception_handling'),
    path('java_interface', java.interface, name='java_interface'),
    path('java_classes_and_objects', java.classes_and_objects, name='java_classes_and_objects'),
    path('java_constructor', java.constructor, name='java_constructor'),
    path('java_inheritance', java.inheritance, name='java_inheritance'),
    path('java_access_modifier', java.access_modifier, name='java_access_modifier'),
    path('java_overlaoding_and_overriding', java.overlaoding_and_overriding, name='java_overloading_and_overriding'),
    path('java_polymorphism', java.polymorphism, name='java_polymorphism'),
    path('java_encapsulation', java.encapsulation, name='java_encapsulation'),
    path('java_packages', java.packages, name='java_packages'),
    path('python_introduction', python.introduction, name='python_introduction'),
    path('python_environment_setup', python.environment_setup, name='python_environment_setup'),
    path('python_basic_syntax', python.basic_syntax, name='python_basic_syntax'),
    path('python_data_types', python.data_types, name='python_data_types'),
    path('python_operators', python.operators, name='python_operators'),
    path('python_decision_making', python.decision_making, name='python_decision_making'),
    path('python_loops', python.loops, name='python_loops'),
    path('python_function', python.function, name='python_function'),
    path('python_modules', python.modules, name='python_modules'),
    path('python_basic_input_output', python.basic_input_output, name='python_basic_input_output'),
    path('python_exception_handling', python.exception_handling, name='python_exception_handling'),
    path('python_file_handling', python.file_handling, name='python_file_handling'),
    path('python_classes_and_objects', python.classes_and_objects, name='python_classes_and_objects'),
    path('python_constructor', python.constructor, name='python_constructor'),
    path('python_inheritance', python.inheritance, name='python_inheritance'),
    path('python_overlaoding_and_overriding', python.overlaoding_and_overriding, name='python_overloading_and_overriding'),
    path('python_data_hiding', python.data_hiding, name='python_data_hiding'),
    path('python_regular_expression', python.regular_expression, name='python_regular_expression'),
    path('html_introduction', html.introduction, name='html_introduction'),
    path('html_basic_tags', html.basic_tags, name='html_basic_tags'),
    path('html_elements', html.elements, name='html_elements'),
    path('html_attribute', html.attribute, name='html_attribute'),
    path('html_formatting', html.formatting, name='html_formatting'),
    path('html_meta_tags', html.meta_tags, name='html_meta_tags'),
    path('html_comment', html.comment, name='html_comment'),
    path('html_image', html.image, name='html_image'),
    path('html_table', html.table, name='html_table'),
    path('html_list', html.list, name='html_list'),
    path('html_link', html.link, name='html_link'),
    path('html_block', html.block, name='html_block'),
    path('html_classes', html.classes, name='html_classes'),
    path('html_id', html.id, name='html_id'),
    path('html_form', html.form, name='html_form'),
    path('html_stylesheet', html.stylesheet, name='html_stylesheet'),
    path('html_javascript', html.javascript, name='html_javascript'),
    path('css_introduction', css.introduction, name='css_introduction'),
    path('css_basic_syntax', css.basic_syntax, name='css_basic_syntax'),
    path('css_colors', css.colors, name='css_colors'),
    path('css_background', css.background, name='css_background'),
    path('css_font', css.font, name='css_font'),
    path('css_text', css.text, name='css_text'),
    path('css_image', css.image, name='css_image'),
    path('css_link', css.link, name='css_link'),
    path('css_table', css.table, name='css_table'),
    path('css_border', css.border, name='css_border'),
    path('css_margin', css.margin, name='css_margin'),
    path('css_list', css.list, name='css_list'),
    path('css_padding', css.padding, name='css_padding'),
    path('css_box_model', css.box_model, name='css_box_model'),
    path('css_height_and_width', css.height_and_width, name='css_height_and_width'),
    path('css_pseudo_class', css.pseudo_class, name='css_pseudo_class'),
    path('css_pseudo_element', css.pseudo_element, name='css_pseudo_element'),
    path('css_rounded_corner', css.rounded_corner, name='css_rounded_corner'),

]