# Generated by Django 2.1.7 on 2019-03-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=1000)),
                ('mobile_number', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
